QMAKE_LIBS_EGL         += -lEGL
QMAKE_LIBS_OPENGL_ES2  += -lGLESv2 -lEGL

QMAKE_CFLAGS           += $$RPI_CFLAGS
QMAKE_CXXFLAGS         += $$RPI_CFLAGS

QMAKE_PLATFORM         += boot2qt
QT_QPA_DEFAULT_PLATFORM = wayland
EGLFS_DEVICE_INTEGRATION = eglfs_kms
